import { Platform, StatusBar as NativeStatusBar, StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#f6f7f9' },
  androidSafeArea: { paddingTop: Platform.OS === 'android' ? NativeStatusBar.currentHeight || 0 : 0 },
  screen: { flex: 1 },
  header: { paddingHorizontal: 20, paddingTop: 10, paddingBottom: 14 },
  appName: { color: '#172033', fontSize: 30, fontWeight: '700' },
  subtitle: { color: '#5d6678', fontSize: 14, lineHeight: 20, marginTop: 6 },
  homeContent: { gap: 14, padding: 16, paddingBottom: 32 },
  featureCard: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: '#dfe3ea',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    minHeight: 92,
    padding: 14,
  },
  featureIcon: {
    alignItems: 'center',
    backgroundColor: '#edf3ff',
    borderRadius: 8,
    height: 48,
    justifyContent: 'center',
    width: 48,
  },
  featureIconMuted: {
    alignItems: 'center',
    backgroundColor: '#eef1f5',
    borderRadius: 8,
    flexDirection: 'row',
    gap: 4,
    height: 48,
    justifyContent: 'center',
    width: 48,
  },
  copyIconBack: {
    backgroundColor: '#dbe7ff',
    borderColor: '#9bb4ff',
    borderRadius: 4,
    borderWidth: 1.5,
    height: 23,
    left: 12,
    position: 'absolute',
    top: 11,
    width: 22,
  },
  copyIconFront: {
    backgroundColor: '#ffffff',
    borderColor: '#155eef',
    borderRadius: 4,
    borderWidth: 1.5,
    height: 23,
    position: 'absolute',
    right: 11,
    top: 16,
    width: 22,
  },
  moreIconDot: { backgroundColor: '#4b5563', borderRadius: 3, height: 6, width: 6 },
  featureTextBlock: { flex: 1, minWidth: 0 },
  featureTitle: { color: '#172033', fontSize: 17, fontWeight: '800' },
  featureSubtitle: { color: '#5d6678', fontSize: 13, lineHeight: 18, marginTop: 4 },
  navigationHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 14,
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 10,
  },
  pageTitle: { color: '#172033', fontSize: 22, fontWeight: '700' },
  pageSubtitle: { color: '#6b7280', fontSize: 13, marginTop: 2 },
  content: { gap: 14, padding: 16, paddingBottom: 112 },
  panel: {
    backgroundColor: '#ffffff',
    borderColor: '#dfe3ea',
    borderRadius: 8,
    borderWidth: 1,
    padding: 14,
  },
  panelHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  panelTitle: { color: '#172033', fontSize: 18, fontWeight: '700' },
  photoSummary: { alignItems: 'center', flexDirection: 'row', gap: 12, marginTop: 14 },
  thumbnail: { backgroundColor: '#e8ecf2', borderRadius: 6, height: 76, width: 76 },
  photoInfo: { flex: 1, minWidth: 0 },
  photoName: { color: '#172033', fontSize: 15, fontWeight: '600' },
  photoDetail: { color: '#6b7280', fontSize: 13, marginTop: 4 },
  panelMessage: { color: '#8a5a00', fontSize: 13, lineHeight: 18, marginTop: 12 },
  metadataPreview: {
    backgroundColor: '#ffffff',
    borderColor: '#dfe3ea',
    borderRadius: 8,
    borderWidth: 1,
    padding: 12,
  },
  previewRow: { alignItems: 'center', flexDirection: 'row', gap: 12, minHeight: 30 },
  previewLabel: { color: '#5d6678', fontSize: 13, width: 68 },
  previewValue: { color: '#172033', flex: 1, fontSize: 14 },
  targetCount: { color: '#172033', fontSize: 15, marginTop: 14 },
  thumbStrip: { gap: 8, paddingTop: 12 },
  targetThumb: { backgroundColor: '#e8ecf2', borderRadius: 6, height: 58, width: 58 },
  moreThumb: {
    alignItems: 'center',
    backgroundColor: '#e8ecf2',
    borderRadius: 6,
    height: 58,
    justifyContent: 'center',
    width: 58,
  },
  moreThumbText: { color: '#4b5563', fontSize: 14, fontWeight: '700' },
  emptyText: { color: '#8a93a3', fontSize: 14, marginTop: 14 },
  bottomBar: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderTopColor: '#dfe3ea',
    borderTopWidth: 1,
    bottom: 0,
    flexDirection: 'row',
    gap: 12,
    left: 0,
    padding: 16,
    position: 'absolute',
    right: 0,
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: '#155eef',
    borderRadius: 8,
    flex: 1,
    minHeight: 48,
    justifyContent: 'center',
  },
  primaryButtonText: { color: '#ffffff', fontSize: 16, fontWeight: '700' },
  secondaryButton: { backgroundColor: '#edf3ff', borderRadius: 8, paddingHorizontal: 14, paddingVertical: 9 },
  secondaryButtonText: { color: '#155eef', fontSize: 14, fontWeight: '700' },
  textButton: {
    backgroundColor: '#ffffff',
    borderColor: '#dfe3ea',
    borderRadius: 8,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  textButtonLabel: { color: '#155eef', fontSize: 14, fontWeight: '700' },
  disabledButton: { opacity: 0.58 },
  pressed: { opacity: 0.82 },
  group: {
    backgroundColor: '#ffffff',
    borderColor: '#dfe3ea',
    borderRadius: 8,
    borderWidth: 1,
    overflow: 'hidden',
  },
  groupTitle: {
    backgroundColor: '#f1f4f8',
    color: '#172033',
    fontSize: 16,
    fontWeight: '700',
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  optionRow: {
    alignItems: 'center',
    borderTopColor: '#edf0f5',
    borderTopWidth: 1,
    flexDirection: 'row',
    gap: 12,
    minHeight: 76,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  optionDisabled: { opacity: 0.48 },
  optionTextBlock: { flex: 1, minWidth: 0 },
  optionTitleRow: { alignItems: 'center', flexDirection: 'row', gap: 8 },
  optionLabel: { color: '#172033', fontSize: 15, fontWeight: '700' },
  optionTag: { color: '#6b7280', fontSize: 12, marginTop: 3 },
  optionValue: { color: '#3f4654', fontSize: 13, marginTop: 5 },
  riskBadge: {
    backgroundColor: '#fff3d8',
    borderRadius: 6,
    color: '#8a5a00',
    fontSize: 11,
    fontWeight: '700',
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  notice: {
    backgroundColor: '#fff',
    borderColor: '#dfe3ea',
    borderRadius: 8,
    borderWidth: 1,
    padding: 14,
  },
  noticeTitle: { color: '#172033', fontSize: 15, fontWeight: '700' },
  noticeText: { color: '#5d6678', fontSize: 14, lineHeight: 20, marginTop: 6 },
  moreSection: {
    backgroundColor: '#ffffff',
    borderColor: '#dfe3ea',
    borderRadius: 8,
    borderWidth: 1,
    padding: 14,
  },
  moreSectionTitle: { color: '#172033', fontSize: 16, fontWeight: '800' },
  moreSectionText: { color: '#5d6678', fontSize: 14, lineHeight: 20, marginTop: 6 },
  resultRow: {
    alignItems: 'flex-start',
    backgroundColor: '#ffffff',
    borderColor: '#dfe3ea',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    padding: 12,
  },
  resultTextBlock: { flex: 1, minWidth: 0 },
  resultTitle: { color: '#172033', fontSize: 15, fontWeight: '700' },
  resultDetail: { color: '#5d6678', fontSize: 13, lineHeight: 18, marginTop: 4 },
  resultWarning: { color: '#8a5a00', fontSize: 13, lineHeight: 18, marginTop: 4 },
  successBadge: {
    backgroundColor: '#dcfce7',
    borderRadius: 6,
    color: '#166534',
    fontSize: 12,
    fontWeight: '700',
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  failBadge: {
    backgroundColor: '#fee2e2',
    borderRadius: 6,
    color: '#991b1b',
    fontSize: 12,
    fontWeight: '700',
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  partialBadge: {
    backgroundColor: '#fff3d8',
    borderRadius: 6,
    color: '#8a5a00',
    fontSize: 12,
    fontWeight: '700',
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  dialogOverlay: {
    alignItems: 'center',
    backgroundColor: 'rgba(23, 32, 51, 0.46)',
    flex: 1,
    justifyContent: 'center',
    padding: 24,
  },
  dialogCard: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 8,
    maxWidth: 420,
    paddingHorizontal: 20,
    paddingVertical: 22,
    width: '100%',
  },
  dialogIcon: {
    alignItems: 'center',
    borderRadius: 18,
    height: 36,
    justifyContent: 'center',
    marginBottom: 12,
    width: 36,
  },
  dialogIconInfo: { backgroundColor: '#dbeafe' },
  dialogIconWarning: { backgroundColor: '#fff3d8' },
  dialogIconError: { backgroundColor: '#fee2e2' },
  dialogIconText: { color: '#172033', fontSize: 18, fontWeight: '800' },
  dialogTitle: { color: '#172033', fontSize: 18, fontWeight: '800', textAlign: 'center' },
  dialogMessage: { color: '#5d6678', fontSize: 14, lineHeight: 21, marginTop: 8, textAlign: 'center' },
  dialogButton: {
    alignItems: 'center',
    backgroundColor: '#155eef',
    borderRadius: 8,
    justifyContent: 'center',
    marginTop: 18,
    minHeight: 44,
    width: '100%',
  },
  dialogButtonText: { color: '#ffffff', fontSize: 15, fontWeight: '700' },
  pickerCard: {
    backgroundColor: '#ffffff',
    borderRadius: 8,
    maxWidth: 420,
    padding: 16,
    width: '100%',
  },
  pickModeButton: {
    alignItems: 'center',
    borderColor: '#dfe3ea',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    marginTop: 12,
    minHeight: 66,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  pickModeIcon: {
    alignItems: 'center',
    backgroundColor: '#edf3ff',
    borderRadius: 8,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  pickModeIconText: { color: '#155eef', fontSize: 15, fontWeight: '800' },
  pickModeTextBlock: { flex: 1, minWidth: 0 },
  pickModeTitle: { color: '#172033', fontSize: 15, fontWeight: '800' },
  pickModeSubtitle: { color: '#6b7280', fontSize: 13, marginTop: 3 },
  cancelButton: {
    alignItems: 'center',
    borderColor: '#dfe3ea',
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    marginTop: 12,
    minHeight: 44,
  },
  cancelButtonText: { color: '#3f4654', fontSize: 15, fontWeight: '700' },
});
